services:
    dtc_queue.document.grid.source.job:
        class: Dtc\QueueBundle\Grid\JobDocumentGridSource
        arguments:
            - '@dtc_queue.job_manager.mongodb'
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]
    dtc_queue.entity.grid.source.job:
        class: Dtc\QueueBundle\Grid\JobEntityGridSource
        arguments:
            - '@dtc_queue.job_manager.orm'
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]

