services:
    dtc_queue.document.grid.source.job:
        class: Dtc\GridBundle\Grid\Source\DocumentGridSource
        arguments:
            - '@dtc_queue.document_manager'
            - Dtc\QueueBundle\Document\Job
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]
    dtc_queue.document.grid.source.job_archive:
        class: Dtc\GridBundle\Grid\Source\DocumentGridSource
        arguments:
            - '@dtc_queue.document_manager'
            - Dtc\QueueBundle\Document\JobArchive
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]
    dtc_queue.entity.grid.source.job:
        class: Dtc\GridBundle\Grid\Source\EntityGridSource
        arguments:
            - '@dtc_queue.entity_manager'
            - Dtc\QueueBundle\Entity\Job
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]
    dtc_queue.entity.grid.source.job_archive:
        class: Dtc\GridBundle\Grid\Source\EntityGridSource
        arguments:
            - '@dtc_queue.entity_manager'
            - Dtc\QueueBundle\Entity\JobArchive
        tags: [{ name: dtc_grid.source }]
        calls: [[autoDiscoverColumns]]
