queue:
    resource: "@DtcQueueBundle/Controller/QueueController.php"
    prefix:  /dtc_queue/
    type: annotation

queue_action:
    resource: "@DtcQueueBundle/Controller/QueueActionController.php"
    prefix:  /dtc_queue/
    type: annotation

queue_trends:
    resource: "@DtcQueueBundle/Controller/TrendsController.php"
    prefix:  /dtc_queue/
    type: annotation

