language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0

services: mongodb

before_script:
  - printf "\n" | pecl install -f mongo-1.6.11
  - composer self-update
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    - mmucklo@gmail.com
