language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services: mongodb

before_script:
  - pecl install -f mongo-1.6.11
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    - mmucklo@gmail.com
