language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0

services: mongodb
sudo: required

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then printf "\n" | pecl install -f mongo-1.6.12; fi
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then composer require --update-no-dev mongofill/mongofill; fi
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    - mmucklo@gmail.com
