language: php

php:
  - 5.3
  - 5.4

services: mongodb

before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    - davidkmo@gmail.com
